PREFIX ex: <http://ex.org/a#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX qb: <http://purl.org/linked-data/cube#>
PREFIX c19: <http://example.org/ns#>
PREFIX c19-measure: <http://example.org/measure#>
PREFIX c19-interval: <http://example.org/interval#>
PREFIX c19-dimension: <http://example.org/dimension#>
PREFIX c19-unit: <http://example.org/unit#>
PREFIX sdmx-attribute:  <http://purl.org/linked-data/sdmx/2009/attribute#>
PREFIX wd: <http://www.wikidata.org/entity/>
CONSTRUCT { 
  ?obs a qb:Observation;
    qb:dataSet  c19:dataset-prevalence_child_malnutrition;
    c19-dimension:refPeriod c19-interval:Year2011-19;
    c19-dimension:ageInterval c19-interval:Age0-5 ;
    c19-measure:prevalenceStuntingHeight ?data ;
    sdmx-attribute:unitMultiplier  -2;
    sdmx-attribute:decimals  1;
    c19-dimension:refArea ?wdID;
}
FROM <file:prevalence_child_malnutrition.tsv> 
WHERE {
  BIND (URI(CONCAT('c19:prevalenceStuntingHeight-o0', ?id_row)) AS ?obs)
  BIND (URI(CONCAT('wd:',?ID)) AS ?wdID)
  BIND (xsd:decimal(?Stuntingheightforage) AS ?data)
}
