PREFIX ex: <http://ex.org/a#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX qb: <http://purl.org/linked-data/cube#>
PREFIX eg: <http://example.org/ns#>
PREFIX eg-measure: <http://example.org/measure#>
PREFIX sdmx-dimension: <http://ex.org/>
PREFIX wd: <http://www.wikidata.org/entity/>
CONSTRUCT { 
  ?obs a qb:Observation;
    qb:dataSet  eg:dataset-population_density;
    eg:refPeriod eg:Interval2019;
    eg-measure:pop_density ?data ;
    eg:refArea ?egID;
}
FROM <file:population_density.tsv> 
WHERE {
  BIND (URI(CONCAT('eg:population_density-o0', ?id_row)) AS ?obs)
  BIND (URI(CONCAT('eg:',?ID)) AS ?egID)
  BIND (xsd:decimal(?Populationdensity) AS ?data)
}
