PREFIX ex: <http://ex.org/a#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX qb: <http://purl.org/linked-data/cube#>
PREFIX eg: <http://example.org/ns#>
PREFIX eg-measure: <http://example.org/measure#>
PREFIX sdmx-dimension: <http://ex.org/>
PREFIX wd: <http://www.wikidata.org/entity/>
CONSTRUCT { 
  ?obs a qb:Observation;
    qb:dataSet  eg:dataset-prevalence_child_malnutrition;
    eg:refPeriod eg:Interval2011-19;
    eg-measure:prevalence-stunting-height-age ?data ;
    eg:refArea ?egID;
}
FROM <file:prevalence_child_malnutrition.tsv> 
WHERE {
  BIND (URI(CONCAT('eg:prevalence_child_malnutrition-o0', ?id_row)) AS ?obs)
  BIND (URI(CONCAT('eg:',?ID)) AS ?egID)
  BIND (xsd:decimal(?Stuntingheightforage) AS ?data)
}
