PREFIX c19:  <http://example.org/ns#>
PREFIX c19-measure:  <http://example.org/measure#>
PREFIX c19-dimension:  <http://example.org/dimension#>
PREFIX c19-interval: <http://example.org/interval#>
PREFIX wd:  <http://www.wikidata.org/entity/>
PREFIX qb: <http://purl.org/linked-data/cube#>

SELECT ?country ?num_covid
FROM <urn:x-arq:UnionGraph>
WHERE {
   ?obs_covid qb:dataSet  c19:dataset-CSSEConfirmedGlobal ;
   c19-dimension:refPeriod c19-interval:Date20200122-20201027 ;
   c19-dimension:refArea ?country;
   c19-measure:cases ?num_covid.
}
