PREFIX ex: <http://ex.org/a#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX qb: <http://purl.org/linked-data/cube#>
PREFIX eg: <http://example.org/ns#>
PREFIX eg-measure: <http://example.org/measure#>
PREFIX sdmx-dimension: <http://ex.org/>
CONSTRUCT { 
  ?obs a qb:Observation;
    qb:dataSet  "dataset-gross_national_income";
    sdmx-dimension:timePeriod "2019"^^xsd:gYear ;
    eg-measure:dolar_percapita ?data;
    eg:refArea ?ID;
}
FROM <file:gross_national_income.tsv> 
WHERE {
  BIND (URI(CONCAT('eg:gross_national_income-o1', ?id_row)) AS ?obs)
  BIND (xsd:decimal(?percapita) AS ?data)
}
