PREFIX ex: <http://ex.org/a#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX qb: <http://purl.org/linked-data/cube#>
PREFIX eg: <http://example.org/ns#>
PREFIX eg-measure: <http://example.org/measure#>
PREFIX sdmx-dimension: <http://ex.org/>
CONSTRUCT { 
  ?obs a qb:Observation;
    qb:dataSet  "dataset-percentage_share_income";
    eg:refPeriod eg:Interval2006-17;
    eg-measure:percentage_lowest20 ?data;
    eg:refArea ?ID;
}
FROM <file:percentage_share_income.tsv> 
WHERE {
  BIND (URI(CONCAT('eg:percentage_share_income-o0', ?id_row)) AS ?obs)
  BIND (xsd:decimal(?Lowest20) AS ?data)
}
